---
name: deploy-container
on:
  push:
    branches:
      - main
    paths:
      - packages/container/**
defaults:
  run:
    working-directory: packages/container
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - name: Install OCI CLI
        run: >
          curl -L
          https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          | bash -s -- --accept-all-defaults

          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem
          cat > ~/.oci/config <<EOF
          [DEFAULT]
          user=${{ secrets.OCI_USER_OCID }}
          fingerprint=${{ secrets.OCI_FINGERPRINT }}
          key_file=~/.oci/oci_api_key.pem
          tenancy=${{ secrets.OCI_TENANCY_OCID }}
          region=${{ secrets.OCI_REGION }}
          EOF
      - name: Upload to OCI Object Storage
        run: |
          oci os object bulk-upload \
            --bucket-name ${{ secrets.OCI_BUCKET_NAME }} \
            --namespace ${{ secrets.OCI_NAMESPACE }} \
            --src-dir dist \
            --overwrite
